name: Test ckan-docker images (PR)

on:
  pull_request:
    branches:
        - master
        - 'ckan-*.*.*'
        - '!dev/ckan-*.*.*'
        - '!feature/*'
        - '!fix/*'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ckan-docker
    CONTEXT: .
    BRANCH: ${{ github.head_ref }}
    DOCKERFILE_PATH: /ckan
    DOCKERFILE: Dockerfile
    HADOLINT_VERSION: 2.12.0

jobs:
  docker:
    name: runner/test-docker-pr:${{ github.head_ref }}
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code
        uses: actions/checkout@v4

      -  name: NGINX build
         uses: docker/build-push-action@v6
         with:
            context: ./nginx
            file: ./nginx/Dockerfile
            push: false
            tags: mjanez/ckan-docker-nginx:test-build-only

      -  name: Apache HTTP Server build
         uses: docker/build-push-action@v6
         with:
            context: ./apache
            file: ./apache/Dockerfile
            push: false
            tags: mjanez/ckan-docker-apache:test-build-only

      -  name: PostgreSQL build
         uses: docker/build-push-action@v6
         with:
              context: ./postgresql
              file: ./postgresql/Dockerfile
              push: false
              tags: mjanez/ckan-docker-postgresql:test-build-only

      -  name: Solr build
         uses: docker/build-push-action@v6
         with:
              context: ./solr
              file: ./solr/Dockerfile
              push: false
              tags: mjanez/ckan-docker-solr:test-build-only

      -  name: ckan-pycsw build
         uses: docker/build-push-action@v6
         with:
              context: ./ckan-pycsw
              file: ./ckan-pycsw/Dockerfile
              push: false
              tags: mjanez/ckan-docker-pycsw:test-build-only

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Linting Dockerfiles and annotate code inline in the github PR viewer
        id: hadolint
        uses: jbergstroem/hadolint-gh-action@v1.12.2
        with:
          dockerfile: ${{ env.CONTEXT }}${{ env.DOCKERFILE_PATH }}/${{ env.DOCKERFILE }} ${{ env.CONTEXT }}${{ env.DOCKERFILE_PATH }}/${{ env.DOCKERFILE }}.ghcr
          version: ${{ env.HADOLINT_VERSION }}
          annotate: true
          error_level: -1